#!/opt/local/bin/bash
# .bashrc
#
# For interactive non-login shells and non-interactive non-login ssh shells.
# 
# For login shells (interactive or not) see first existent of
# ~/.bash_profile, ~/.bash_login and ~/.profile.
# 
# For other non-interactive non-login shells see $BASH_ENV.  At present, this
# is sourced by ~/.profile so runs for all interactive shells (login or not).
# If the shell isn't actually interactive it is an ssh session, and we want
# to source /etc/profile and ~/.profile instead. We can't use a simple test
# of $PS1 and must test $- because /etc/bashrc (also sourced when bash
# detects ssh) sets $PS1. (We empty it here.)
##

if echo $- | grep -q i ; then : ; else
    [ -r /etc/profile ] && source /etc/profile
    PS1=
    source ~/.profile
    return
fi
