##
# Cloud Environment Setup
#
# Copyright 2011-2013 by Andrew Kennedy; All Rights Reserved
#
# Author: andrew.international@gmail.com
# Last Modified: 2013-02-19 12:11
##

##
# Amazon AWS EC2
##

AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""

export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY

JCLOUDS_IDENTITY_AWS_EC2=${AWS_ACCESS_KEY_ID}
JCLOUDS_CREDENTIAL_AWS_EC2=${AWS_SECRET_ACCESS_KEY}
JCLOUDS_IDENTITY_AWS_S3=${AWS_ACCESS_KEY_ID}
JCLOUDS_CREDENTIAL_AWS_S3=${AWS_SECRET_ACCESS_KEY}

export JCLOUDS_IDENTITY_AWS_EC2 JCLOUDS_CREDENTIAL_AWS_EC2
export JCLOUDS_IDENTITY_AWS_S3 JCLOUDS_CREDENTIAL_AWS_S3

##
# Ninefold
##

NINEFOLD_IDENTITY=""
NINEFOLD_CREDENTIAL="="

export NINEFOLD_IDENTITY NINEFOLD_CREDENTIAL

JCLOUDS_IDENTITY_NINEFOLD_STORAGE=${NINEFOLD_IDENTITY}
JCLOUDS_CREDENTIAL_NINEFOLD_STORAGE=${NINEFOLD_CREDENTIAL}

export JCLOUDS_IDENTITY_NINEFOLD_STORAGE JCLOUDS_CREDENTIAL_NINEFOLD_STORAGE

##
# Filesystem
##

JCLOUDS_IDENTITY_FILESYSTEM=""
JCLOUDS_CREDENTIAL_FILESYSTEM=""

export JCLOUDS_IDENTITY_FILESYSTEM JCLOUDS_CREDENTIAL_FILESYSTEM

##
# Greenhouse Data
##

GREENHOUSEDATA_IDENTITY=""
GREENHOUSEDATA_CREDENTIAL=""
GREENHOUSEDATA_ORGANIZATION=""
GREENHOUSEDATA_ENDPOINT="https://mycloud.greenhousedata.com/api"

export GREENHOUSEDATA_IDENTITY GREENHOUSEDATA_CREDENTIAL GREENHOUSEDATA_ORGANISATION GREENHOUSEDATA_ENDPOINT

JCLOUDS_IDENTITY_GREENHOUSEDATA_ELEMENT_VCLOUD_STORAGE=${GREENHOUSEDATA_IDENTITY}
JCLOUDS_CREDENTIAL_GREENHOUSEDATA_ELEMENT_VCLOUD_STORAGE=${GREENHOUSEDATA_CREDENTIAL}
JCLOUDS_IDENTITY_GREENHOUSEDATA_ELEMENT_VCLOUD=${GREENHOUSEDATA_IDENTITY}
JCLOUDS_CREDENTIAL_GREENHOUSEDATA_ELEMENT_VCLOUD=${GREENHOUSEDATA_CREDENTIAL}

export JCLOUDS_IDENTITY_GREENHOUSEDATA_ELEMENT_VCLOUD_STORAGE JCLOUDS_CREDENTIAL_GREENHOUSEDATA_ELEMENT_VCLOUD_STORAGE
export JCLOUDS_IDENTITY_GREENHOUSEDATA_ELEMENT_VCLOUD JCLOUDS_CREDENTIAL_GREENHOUSEDATA_ELEMENT_VCLOUD

function greenhousedata_login() {
    VCLOUD_AUTHORIZATION_HEADER="x-vcloud-authorization"
    VCLOUD_TOKEN=$(curl -X POST -u "${GREENHOUSEDATA_IDENTITY}@${GREENHOUSEDATA_ORGANIZATION}:${GREENHOUSEDATA_CREDENTIAL}" \
        ${GREENHOUSEDATA_ENDPOINT}/sessions -I 2> /dev/null |
        grep "^${VCLOUD_AUTHORIZATION_HEADER}: " |
        cut -d\  -f2)
    if [ "x$1x" = "x-vx" ]; then
        echo "${VCLOUD_AUTHORIZATION_HEADER} = ${VCLOUD_TOKEN}"
    fi
}

function greenhousedata_api() {
    METHOD="$1"
    COMMAND="$2"
    shift; shift; CURL_OPTS="$*"
    greenhousedata_login
    curl -X ${METHOD} -u "${GREENHOUSEDATA_IDENTITY}@${GREENHOUSEDATA_ORGANIZATION}:${GREENHOUSEDATA_CREDENTIAL}" \
        ${CURL_OPTS:="-i"} \
        -H"${VCLOUD_AUTHORIZATION_HEADER}: ${VCLOUD_TOKEN}" \
        ${GREENHOUSEDATA_ENDPOINT}${COMMAND}
}

##
# Bluelock vCloud 1.5 Beta
##

BLUELOCK_BETA_IDENTITY=""
BLUELOCK_BETA_CREDENTIAL=""
BLUELOCK_BETA_ORGANIZATION=""
BLUELOCK_BETA_ENDPOINT="https://vcloudbeta.bluelock.com/api"

export BLUELOCK_BETA_IDENTITY BLUELOCK_BETA_CREDENTIAL BLUELOCK_BETA_ORGANIZATION BLUELOCK_BETA_ENDPOINT

JCLOUDS_IDENTITY_BLUELOCK_BETA=${BLUELOCK_BETA_IDENTITY}
JCLOUDS_CREDENTIAL_BLUELOCK_BETA=${BLUELOCK_BETA_CREDENTIAL}

export JCLOUDS_IDENTITY_BLUELOCK_BETA JCLOUDS_CREDENTIAL_BLUELOCK_BETA

function bluelock_login() {
    VCLOUD_AUTHORIZATION_HEADER="x-vcloud-authorization"
    VCLOUD_TOKEN=$(curl -X POST -u "${BLUELOCK_BETA_IDENTITY}@${BLUELOCK_BETA_ORGANIZATION}:${BLUELOCK_BETA_CREDENTIAL}" \
        ${BLUELOCK_BETA_ENDPOINT}/sessions -I 2> /dev/null |
        grep "^${VCLOUD_AUTHORIZATION_HEADER}: " |
        cut -d\  -f2)
    if [ "x$1x" = "x-vx" ]; then
        echo "${VCLOUD_AUTHORIZATION_HEADER} = ${VCLOUD_TOKEN}"
    fi
}

function bluelock_api() {
    METHOD="$1"
    COMMAND="$2"
    shift; shift; CURL_OPTS="$*"
    bluelock_login
    curl -X ${METHOD} -u "${BLUELOCK_BETA_IDENTITY}@${BLUELOCK_BETA_ORGANIZATION}:${BLUELOCK_BETA_CREDENTIAL}" \
        -H"${VCLOUD_AUTHORIZATION_HEADER}: ${VCLOUD_TOKEN}" \
        ${CURL_OPTS:="-i"} \
        ${BLUELOCK_BETA_ENDPOINT}${COMMAND} 
}

function bluelock_live_test() {
    TEST=
    TEST_OPTS=
    if [ $# -gt 0 ]; then
        TEST=${1}ClientLiveTest
        shift;
        TEST_OPTS=$*
    fi
    BLUELOCK_BETA_CATALOG_NAME=QunyingTestCatalog
    CMD="mvn clean install -Plive \
        -Dtest.vcloud-director.identity=${BLUELOCK_BETA_IDENTITY}@${BLUELOCK_BETA_ORGANIZATION} \
        -Dtest.vcloud-director.credential=${BLUELOCK_BETA_CREDENTIAL} \
        -Dtest.vcloud-director.endpoint=${BLUELOCK_BETA_ENDPOINT} \
        -Dtest.vcloud-director.catalog-name=${BLUELOCK_BETA_CATALOG_NAME}"
    if [ ! -z "${TEST}" ]; then
        CMD="${CMD} -Dtest=${TEST}"
    fi
    CMD="${CMD} ${TEST_OPTS}"
    echo "${CMD}"
    ${CMD} || open target/surefire-reports/index.html
}

# vim:ts=4:sw=4
